### ISSUE TITLE
isomir naming

### ISSUE THREAD

**Issue by lpantano** [miRTop/incubator#1]
Here, people can ask, discuss about the isomir naming document it is in this repository:

https://github.com/miRTop/incubator/blob/master/isomirs/isomir_naming.md

It will end with the first version of the isomir naming and file format for bioinformatics tools and mentioning in papers.

If you want to join and provide your ideas on idomiR naming and things to pay attention to, please just comment in this issue.

**Comment by lpantano** [comment]
Hi @ThomasDesvignes and @keilbeck,

do you think that it would be good to start reaching people that may help with miRNA/isomiR naming using the web-page as a presentation (http://mirtop.github.io/). I liked the discussion in this document, but a couple of more inputs would be good. 

If we don't have input, I will add my suggest to the document, and we could start with the tool that parses BAM files and create the naming we agree. Maybe this helps to call attention from other people. 

cheers

**Comment by BastianFromm** [comment]
yes

**Comment by lpantano** [comment]
Moved to: https://github.com/miRTop/incubator/issues/11
