### ISSUE TITLE
Submit work to BOSC2018

### ISSUE THREAD

**Issue by lpantano** [miRTop/incubator#18]
Hi all

I plan to submit abstract for BOSC2018: https://gccbosc2018.sched.com. I will send the draft and incorporate the feedback but probably after submitting because the deadline is on Friday. I need to know if somebody oppose to this. I’ll add all people that have been involved from the beginning in order of contribution. BTW, all of you can present this whenever you want.

I'll use the affiliation here to add you as authors: http://mirtop.github.io. If you are not there, or want to change something let me know. 

cc:@lpantano @gurgese @ThomasDesvignes @mhalushka @mlhack @keilbeck @BastianFromm @ivlachos @TJU-CMC @phillipeloher

**Comment by BastianFromm** [comment]
Hi Lorena,

I would be very happy to see the direction the abstract would go before you
submit it.
Thanks
Bastian

_____________________________________________________________________________________

Dr. Bastian Fromm (PhD)

PostDoc
Department of Tumor Biology
Institute for Cancer Research
Norwegian Radium Hospital
Oslo University Hospital
PO Box 4950 Nydalen
0424 Oslo
Norway

Room: K05, 072

tel: +47 22 78 18 73
cell: +47 94 12 29 55
eMail: bastianfromm@gmail.com, bastian.fromm@rr-research.no
DB: http://www.mirgenedb.org/

profiles  Linkedin <https://www.linkedin.com/in/bastian-fromm-90286843/>
Loop <http://loop.frontiersin.org/people/399448/overview> Mendeley
<https://www.mendeley.com/profiles/bastian-fromm/> ORCID
<http://orcid.org/0000-0003-0352-3037> Publons
<https://publons.com/author/306130/bastian-fromm#profile> Researchgate
<https://www.researchgate.net/profile/Bastian_Fromm2> Scopus
<https://www.scopus.com/authid/detail.uri?authorId=25030115200> Twitter
<https://twitter.com/@BastianFromm> Xing
<https://www.xing.com/profile/Bastian_Fromm?sc_o=mxb_p>





_____________________________________________________________________________________

**Comment by lpantano** [comment]
This is a preliminary version, feel free to comment in any thing:

https://docs.google.com/document/d/1F6wuOSzQb-waIHILnxtf95HmdxfUpVCjBMRgWoBn-zw/edit

**Comment by lpantano** [comment]
The work has been accepted for long talk: 17min + 3m questions.

Thanks a lot.

I'll try to post the slides here with enough times for you to review. Probably, early June.

Please, post here the logo you want me to use in the acknowledgement slide.

**Comment by keilbeck** [comment]
Great news Lorena

**Comment by ivlachos** [comment]
Congrats Lorena!

**Comment by BastianFromm** [comment]
excellent!

_____________________________________________________________________________________

Dr. Bastian Fromm (PhD)

PostDoc
Department of Tumor Biology
Institute for Cancer Research
Norwegian Radium Hospital
Oslo University Hospital
PO Box 4950 Nydalen
0424 Oslo
Norway

Room: K05, 072

tel: +47 22 78 18 73
cell: +47 94 12 29 55
eMail: bastianfromm@gmail.com, bastian.fromm@rr-research.no
DB: http://www.mirgenedb.org/

profiles  Linkedin <https://www.linkedin.com/in/bastian-fromm-90286843/>
Loop <http://loop.frontiersin.org/people/399448/overview> Mendeley
<https://www.mendeley.com/profiles/bastian-fromm/> ORCID
<http://orcid.org/0000-0003-0352-3037> Publons
<https://publons.com/author/306130/bastian-fromm#profile> Researchgate
<https://www.researchgate.net/profile/Bastian_Fromm2> Scopus
<https://www.scopus.com/authid/detail.uri?authorId=25030115200> Twitter
<https://twitter.com/@BastianFromm> Xing
<https://www.xing.com/profile/Bastian_Fromm?sc_o=mxb_p>





_____________________________________________________________________________________

**Comment by ThomasDesvignes** [comment]
Congrats Lorena!

**Comment by lpantano** [comment]
Hi all,

I am preparing the slides for next week talk:

https://docs.google.com/presentation/d/1Nyk6xHL80pHglLYrv5XJ9a8FExjpHpnGAdkVhZSbJrk/edit?usp=sharing

Right now is just the skeleton of the talk, but if you visit in a couple of days, it should be fairly done.

Thanks in advance!

**Comment by keilbeck** [comment]
Thanks for sharing.
It looks good. Let me know if you need help with anything. Maybe figures?
Cheers,
K

**Comment by mhalushka** [comment]
If I can be of any help, let me know.

**Comment by ivlachos** [comment]
The outline makes sense and seems to cover everything.

I'll keep an eye on the google doc.

Let me know if there is anything I can do to help.

**Comment by ivlachos** [comment]
Sorry! my bad. Closed it by mistake.

**Comment by lpantano** [comment]
Hi all again,

I updated the slides, I don't think I would move a lot from this, but I made some comments and happy to accept any comments or slides. Just modify directly using the link:

https://docs.google.com/presentation/d/1Nyk6xHL80pHglLYrv5XJ9a8FExjpHpnGAdkVhZSbJrk/edit?usp=sharing

@keilbeck don't know if you want to explain better the GFF3 slide

If somebody wants to make a better figure for isomiRs scheme go ahead please. Maybe just reply here to say you'll do it.

The talk is on Jun 27, 1:44pm, so I'll freeze slides the day before that, on Jun 26, 8pm PST.

Please add at the end the logo of your institution, or the name and a picture of you, if you want.

I think this is all for now.

Thanks!

**Comment by mhalushka** [comment]
Lorena,
    You did a great job on this. I added and commented on a few things. I don't know if you can make the font bigger on slides 17-19.  They won't project well.  Thanks for doing all of this.
Marc

**Comment by xbdr86** [comment]
Hi!

Nice job! My suggestion is that slides 18:20 are pretty information dense, maybe you want to add some animations or comments to focus the attention of the audience to certain aspects of the multiple plots.

Good luck!

Xavi

**Comment by ThomasDesvignes** [comment]
Hi Lorena!
I'm back from Antarctica so I now have a better connection and also more time!
I've made a few minor comments and I think it's looking good! 
Thanks for getting all this together and being the driver of this great project!
Cheers!
Thomas
PS: contact me if you end up visiting Oregon after the meeting!

**Comment by lpantano** [comment]
Thanks all for the comments, I'll try to address all of them and try to add some notes to explain better the figures.
If somebody didn't add the logo, please do :) @phillipeloher?

@ThomasDesvignes, I'll be in Portland downtown Saturday afternoon until 8pm, mainly in the powell book store :P

**Comment by phillipeloher** [comment]
Looks good @lpantano , good job!  Added Jefferson's logo.  Not sure when we need the develop the details of the isomiR annotations (e.g. slide 10) - where is the most appropriate place (email?) for suggestions there?

**Comment by lpantano** [comment]
Awesome! You can discuss in GitHub using an issue, this is the main document for now: https://github.com/miRTop/incubator/blob/master/format/definition.md

**Comment by lpantano** [comment]
Slides are done, I am submitting to F1000 to have it as a record and all of you can cite. I'll post the link one is up there.

**Comment by lpantano** [comment]
Hi,

All of you can cite the talk using this: http://dx.doi.org/10.7490/f1000research.1115724.1

Please, help to spread the word about this format and encourage developers to help to support a conversion from the current output to GFF3. 

Remember that any of you can mention this project at any talk, and submit it to any conference.

Cheers
