### ISSUE TITLE
File organization in the Incubator

### ISSUE THREAD

**Issue by ThomasDesvignes** [miRTop/incubator#3]
In order to have the easiest accessibility to the information, I think it would be best that each topic in the incubator would have its own folder in which we could have different files instead of having everything in one file. 
A classic folder/topic would contain files with generic names:
- Topic description (cf my little list in the Incubator README)
- Discussions
- Agreement
- Relevant literature?
  So that people who search for the final info can go straight to the Agreement file

Maybe one file is better, I'm just not very familiar with GitHub yet.

**Comment by lpantano** [comment]
that makes sense. feel free to change it, i will change it otherwise at least by folder and create some of the files there. thanks!
