### ISSUE TITLE
miRNA genes and products nomenclature

### ISSUE THREAD

**Issue by ThomasDesvignes** [miRTop/incubator#4]
Here, people can ask, comment or discuss the miRNA genes and products nomenclature guidelines proposed here:
https://github.com/miRTop/incubator/blob/master/microRNA%20Nomenclature.md

Please tell us what you think an appropriate miRNA name should contain, which information it should convey, and tell us your ideas and what matters to you!

**Comment by BastianFromm** [comment]
Is this a discussion or is this decided?

**Comment by lpantano** [comment]
Still discussion. Mainly in the other issue we opened yesterday!

**Comment by BastianFromm** [comment]
great. I answered in the other thread because I could not answer here: https://github.com/miRTop/incubator/blob/master/microRNA%20Nomenclature.md

**Comment by lpantano** [comment]
https://github.com/miRTop/incubator/issues/11
